# cbindgen.toml
language = "C"
pragma_once = true
include_guard = "AHOCORASICK_CAPI_H"
documentation = true
usize_is_size_t = true
sys_includes = ["stddef.h", "stdint.h", "stdbool.h"]

# C typedef-style for enums/structs/unions
style = "type"  # valid: "both" | "tag" | "type"

[export]
include = ["ffi"]

[defines]
# "std" = "AHOCORASICK_HAVE_STD"

[macro_expansion]
bitflags = true

[enum]
# only meaningful for C++; harmless here
enum_class = false

[parse]
parse_deps = false
clean = true
# include = []
# exclude = []
# extra_bindings = []

[parse.expand]
crates = []
all_features = false
default_features = true
features = []
